#!/usr/bin/env python3
"""Deterministic generator for the reference fixture project (BUILD_PLAN §3.7.5, line 536).

Regenerates ``raw/<RUN_ID>/page-0000.jsonl`` ... ``page-0004.jsonl`` and
``raw/<RUN_ID>/manifest.json`` under this directory, laid out exactly as a
real ``capture_search()`` run would seal them (see
``src/prismabib/capture/writer.py``): each page file is the deterministic,
compact (``sort_keys=True, separators=(",", ":")``) JSON re-encoding of one
``search-results`` envelope, written as a single line, and
``manifest.json`` is a real ``prismabib.capture.manifest.RunManifest``
serialised the same way ``capture_search`` itself writes one.

**Determinism.** Every random choice in this module is drawn from a single
``random.Random(SEED)`` instance threaded explicitly through every generator
function -- never the module-level ``random`` singleton. ``RUN_ID``,
``STARTED_AT``/``FINISHED_AT``, and every cursor token are hardcoded
constants, not derived from the wall clock or from entropy. Re-running this
script from a clean checkout therefore reproduces ``raw/`` byte-for-byte;
``verify_reference_fixture.py`` (this directory) checks that claim directly
by re-running the generator into a temp directory and diffing.

**Content is synthetic.** Every title, abstract, author name, affiliation
name, and DOI below is generated from word banks and templates owned by this
module. None of it is copied from ``tests/fixtures/cassettes/`` -- those
cassettes are used *only* as the structural template (field names, list-vs-
scalar quirks, the pagination envelope) that this generator's output shape
is checked against; see ``verify_reference_fixture.py``.

**Changing this fixture.** BUILD_PLAN §3.7.5: the reference fixture project
is frozen. A PR that edits this generator (or hand-edits ``raw/``, which is
never done -- ``raw/`` is only ever produced by running this file) must
explain why and update every affected golden snapshot in the same commit.
See ``README.md`` in this directory for the eight required edge cases and
where each one lives.

Usage::

    uv run python tests/fixtures/projects/reference/generate_reference_fixture.py
"""

from __future__ import annotations

import base64
import hashlib
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from random import Random
from typing import Any
from urllib.parse import quote

from prismabib.capture.manifest import RunManifest
from prismabib.capture.writer import _write_page
from prismabib.project import Project
from prismabib.query import build_query_for_project
from prismabib.sources.scopus import ScopusClient

FIXTURE_ROOT = Path(__file__).resolve().parent
RAW_DIR = FIXTURE_ROOT / "raw"

#: Frozen, hand-chosen (not generated from the wall clock) run identity --
#: see the module docstring's determinism note.
RUN_ID = "20260115T090000Z-fee5c0de"
RUN_DIR = RAW_DIR / RUN_ID
STARTED_AT = datetime(2026, 1, 15, 9, 0, 0, tzinfo=UTC)
FINISHED_AT = datetime(2026, 1, 15, 9, 4, 0, tzinfo=UTC)
CLIENT_VERSION = "0.1.0"

SEED = 20260115

PAGE_SIZE = 25
TOTAL_RECORDS = 120

# ---------------------------------------------------------------------------
# Edge-case placement (BUILD_PLAN §3.7.5, line 536 -- "hand-built to exercise
# every edge"). Positions are 0-based indices into the full 120-record
# sequence, before it is chunked into pages of PAGE_SIZE. See README.md for
# the resulting (file, entry index) of each one -- generated by
# verify_reference_fixture.py, not hand-maintained, so it can never drift
# from this table.
# ---------------------------------------------------------------------------
EDGE_NO_ABSTRACT = 2
EDGE_SCALAR_AFID = 7
EDGE_NON_ENGLISH = 30
EDGE_MANY_AUTHORS = 40
EDGE_ZERO_KEYWORDS = 55
EDGE_DUPLICATE_DOI_A = 60
EDGE_DUPLICATE_DOI_B = 90
EDGE_PARTIAL_YEAR = 95
EDGE_UNMAPPED_COUNTRY = 115

EDGE_POSITIONS: dict[int, str] = {
    EDGE_NO_ABSTRACT: "no_abstract",
    EDGE_SCALAR_AFID: "scalar_afid",
    EDGE_NON_ENGLISH: "non_english",
    EDGE_MANY_AUTHORS: "many_authors",
    EDGE_ZERO_KEYWORDS: "zero_keywords",
    EDGE_DUPLICATE_DOI_A: "duplicate_doi_a",
    EDGE_DUPLICATE_DOI_B: "duplicate_doi_b",
    EDGE_PARTIAL_YEAR: "partial_year",
    EDGE_UNMAPPED_COUNTRY: "unmapped_country",
}

DUPLICATE_DOI_VALUE = "10.1145/3609015.3609231"

# ---------------------------------------------------------------------------
# Word banks and pools -- all hand-authored for this generator, none copied
# from tests/fixtures/cassettes/.
# ---------------------------------------------------------------------------

_TITLE_WORDS = [
    "Adaptive",
    "Robust",
    "Deep",
    "Convolutional",
    "Spatiotemporal",
    "Recurrent",
    "Attention-Based",
    "Unsupervised",
    "Weakly-Supervised",
    "Self-Supervised",
    "Multimodal",
    "Real-Time",
    "Lightweight",
    "Scalable",
    "Graph-Based",
    "Trajectory-Aware",
    "Pose-Guided",
    "Generative",
    "Contrastive",
    "Federated",
    "Explainable",
    "Uncertainty-Aware",
    "Hierarchical",
    "Cross-Modal",
    "Sparse",
    "Cascade",
    "Two-Stream",
    "Dual-Branch",
    "Edge-Deployed",
    "Domain-Adaptive",
]
_TITLE_NOUNS = [
    "Anomaly Detection",
    "Event Recognition",
    "Behaviour Analysis",
    "Crowd Monitoring",
    "Trajectory Prediction",
    "Scene Understanding",
    "Action Localisation",
    "Object Tracking",
    "Motion Segmentation",
    "Surveillance Analytics",
    "Video Forensics",
    "Activity Recognition",
    "Novelty Detection",
    "Outlier Screening",
    "Threat Assessment",
]
_TITLE_CONTEXTS = [
    "Urban Surveillance Networks",
    "Public Transport Hubs",
    "Retail Environments",
    "Campus Security Systems",
    "Smart City Infrastructure",
    "Traffic Intersections",
    "Industrial Monitoring",
    "Crowded Public Spaces",
    "Airport Terminals",
    "Residential CCTV Deployments",
]
_ABSTRACT_OPENERS = [
    "This paper presents a {adj} framework for {task} in {context}.",
    "We propose a {adj} approach to {task}, evaluated on {context}.",
    "In this work, a {adj} method for {task} is introduced and applied to {context}.",
]
_ABSTRACT_MIDDLES = [
    (
        "The proposed model combines feature extraction with a learned decision "
        "boundary to separate normal and abnormal patterns."
    ),
    (
        "Extensive ablation studies quantify the contribution of each architectural "
        "component to overall detection accuracy."
    ),
    (
        "A benchmark comparison against prior baselines demonstrates consistent gains "
        "in precision and recall across multiple datasets."
    ),
    (
        "The method is designed to operate under limited annotation budgets, relying "
        "primarily on normal-only training data."
    ),
    (
        "Computational cost is analysed alongside accuracy to characterise the "
        "trade-off relevant to deployment on constrained hardware."
    ),
]
_ABSTRACT_CLOSERS = [
    "Results indicate that the approach generalises well across previously unseen scene layouts.",
    (
        "Limitations and directions for future work are discussed, including "
        "robustness to sensor noise and domain shift."
    ),
    (
        "The findings suggest practical applicability to real-world monitoring "
        "pipelines with modest additional engineering effort."
    ),
]

_KEYWORD_PHRASES = [
    "video anomaly detection",
    "surveillance analytics",
    "deep learning",
    "one-class classification",
    "autoencoder",
    "spatiotemporal features",
    "benchmark dataset",
    "real-time processing",
    "transfer learning",
    "attention mechanism",
    "graph neural network",
    "self-supervised learning",
    "weak supervision",
    "crowd analysis",
    "trajectory prediction",
    "convolutional neural network",
    "action recognition",
    "scene understanding",
    "outlier detection",
    "generative adversarial network",
    "pose estimation",
    "object tracking",
    "edge computing",
    "domain adaptation",
    "explainable ai",
    "few-shot learning",
    "contrastive learning",
    "multimodal fusion",
    "event localisation",
    "video forensics",
]

# Institutions: (afid, name, city, country-as-emitted-by-scopus).
# Country strings are picked from variants prismabib.countries recognises,
# except EDGE_UNMAPPED_COUNTRY's institution, deliberately not in that table.
_INSTITUTIONS: list[tuple[str, str, str, str]] = [
    ("60000000", "Northfield Institute of Technology", "Northfield", "United States"),
    ("60000001", "Silverbrook University", "Silverbrook", "United Kingdom"),
    ("60000002", "Cedarline Polytechnic", "Cedarline", "Germany"),
    ("60000003", "Meridian State University", "Meridian City", "France"),
    ("60000004", "Ashcombe Research Center", "Ashcombe", "Japan"),
    ("60000005", "Brightwater College of Engineering", "Brightwater", "China"),
    ("60000006", "Kestrel Hill University", "Kestrel Hill", "South Korea"),
    ("60000007", "Fallowfield Institute of Science", "Fallowfield", "Australia"),
    ("60000008", "Thornbury Technical University", "Thornbury", "Canada"),
    ("60000009", "Redgate Applied Sciences Institute", "Redgate", "Brazil"),
    ("60000010", "Millbrook University", "Millbrook", "India"),
    ("60000011", "Oakendale Polytechnic", "Oakendale", "Spain"),
    ("60000012", "Vesterholm Research Institute", "Vesterholm", "Italy"),
    ("60000013", "Clearwater State College", "Clearwater", "Netherlands"),
    ("60000014", "Grantham University of Technology", "Grantham", "Sweden"),
    ("60000015", "Pinehaven Institute of Informatics", "Pinehaven", "South Africa"),
    ("60000016", "Emberfield University", "Emberfield", "Kenya"),
    ("60000017", "Larkspur Institute of Computing", "Larkspur", "Singapore"),
    ("60000018", "Holloway Applied Research Centre", "Holloway", "Mexico"),
    ("60000019", "Windermere Polytechnic University", "Windermere", "Poland"),
]
_UNMAPPED_INSTITUTION = ("60000020", "Hanseong Advanced Institute", "Seosan", "Korea")

_SURNAMES = [
    "Alderman",
    "Winslow",
    "Castellano",
    "Whitfield",
    "Marchetti",
    "Solberg",
    "Vantongeren",
    "Okafor",
    "Bramwell",
    "Delacroix",
    "Iwasaki",
    "Novakovic",
    "Fenwick",
    "Adeyemi",
    "Kowalczyk",
    "Bergstrom",
    "Nakashima",
    "Renwick",
    "Escobedo",
    "Halvorsen",
    "Thistlewood",
    "Marchand",
    "Osei",
    "Vukovic",
    "Ashworth",
    "Callaghan",
    "Deshmukh",
    "Farnsworth",
    "Grigorescu",
    "Hollis",
    "Ibragimov",
    "Jarrell",
    "Kettering",
    "Larrabee",
    "Moellering",
    "Nkemelu",
    "Overby",
    "Pemberton",
    "Ravensworth",
    "Steinvik",
]
_GIVEN_NAMES = [
    "Elena",
    "Marcus",
    "Priya",
    "Tomasz",
    "Ingrid",
    "Kwame",
    "Yuna",
    "Declan",
    "Amara",
    "Bastian",
    "Rin",
    "Vikram",
    "Saoirse",
    "Andrei",
    "Nadia",
    "Felix",
    "Mireille",
    "Osamu",
    "Beatriz",
    "Callum",
    "Zanele",
    "Henrik",
    "Layla",
    "Dmitri",
    "Freya",
    "Kojo",
    "Isolde",
    "Rafael",
    "Suki",
    "Torsten",
]

# ---------------------------------------------------------------------------
# Record spec model
# ---------------------------------------------------------------------------


@dataclass
class RecordSpec:
    seq: int
    scopus_id: str
    year: int
    cover_date: str
    doi: str | None
    subtype: str
    subtype_description: str
    aggregation_type: str
    edge: str | None = None
    _language: str = "English"
    _country_override: tuple[str, str, str, str] | None = None


def _make_scopus_id(seq: int, edge: str | None) -> str:
    """12-digit synthetic SCOPUS_ID, disjoint from any real cassette id.

    Edge-case records get a reserved, easily-greppable ``9000000000NN``
    block (README.md's location table is keyed on these); every other
    record uses the ``2050470NNNNN`` block.
    """
    if edge is not None:
        edge_index = sorted(EDGE_POSITIONS).index(seq) + 1
        return f"90000000{edge_index:04d}"
    return f"2050470{seq:05d}"


def _make_title(rng: Random, seq: int) -> str:
    adj = rng.choice(_TITLE_WORDS)
    noun = rng.choice(_TITLE_NOUNS)
    context = rng.choice(_TITLE_CONTEXTS)
    pattern = seq % 3
    if pattern == 0:
        return f"{adj} {noun} for {context}"
    if pattern == 1:
        return f"{noun}: A {adj} Approach for {context}"
    return f"Towards {adj} {noun} in {context}"


def _make_abstract(rng: Random, title_context: str) -> str:
    adj = rng.choice(_TITLE_WORDS).lower()
    task = rng.choice(_TITLE_NOUNS).lower()
    opener = rng.choice(_ABSTRACT_OPENERS).format(adj=adj, task=task, context=title_context.lower())
    middle = " ".join(rng.sample(_ABSTRACT_MIDDLES, 2))
    closer = rng.choice(_ABSTRACT_CLOSERS)
    return f"{opener} {middle} {closer}"


def _make_keywords(rng: Random, count: int) -> str:
    return " | ".join(sorted(rng.sample(_KEYWORD_PHRASES, count)))


def _make_author(rng: Random, position: int, affiliation_afids: list[str]) -> dict[str, Any]:
    surname = rng.choice(_SURNAMES)
    given = rng.choice(_GIVEN_NAMES)
    initials = f"{given[0]}."
    authid = f"5{position:010d}"
    orcid_parts = [str(rng.randint(1000, 9999)) for _ in range(4)]
    orcid = "-".join(orcid_parts)
    chosen_afid = rng.choice(affiliation_afids)
    return {
        "@_fa": "true",
        "@seq": str(position + 1),
        "author-url": f"https://api.elsevier.com/content/author/author_id/{authid}",
        "authid": authid,
        "orcid": orcid,
        "authname": f"{surname} {initials}",
        "surname": surname,
        "given-name": given,
        "initials": initials,
        "afid": [{"@_fa": "true", "$": chosen_afid}],
    }


def _make_affiliation(
    institution: tuple[str, str, str, str], *, scalar_afid: bool
) -> dict[str, Any]:
    afid, name, city, country = institution
    return {
        "@_fa": "true",
        "affiliation-url": f"https://api.elsevier.com/content/affiliation/affiliation_id/{afid}",
        "afid": afid if scalar_afid else [afid],
        "affilname": name,
        "affiliation-city": city,
        "affiliation-country": country,
    }


def _entry_links(scopus_id: str) -> list[dict[str, Any]]:
    base = f"https://api.elsevier.com/content/abstract/scopus_id/{scopus_id}"
    return [
        {"@_fa": "true", "@ref": "self", "@href": base},
        {"@_fa": "true", "@ref": "author-affiliation", "@href": f"{base}?field=author,affiliation"},
        {
            "@_fa": "true",
            "@ref": "scopus",
            "@href": f"https://www.scopus.com/inward/record.uri?partnerID=HzOxMe3b&scp={scopus_id}&origin=inward",
        },
        {
            "@_fa": "true",
            "@ref": "scopus-citedby",
            "@href": f"https://www.scopus.com/inward/citedby.uri?partnerID=HzOxMe3b&scp={scopus_id}&origin=inward",
        },
    ]


def build_specs() -> list[RecordSpec]:
    """Build the 120 :class:`RecordSpec` in sequence order (no randomness here)."""
    specs: list[RecordSpec] = []
    years = list(range(2016, 2026))  # cycled; EDGE_PARTIAL_YEAR overrides to 2026
    for seq in range(TOTAL_RECORDS):
        edge = EDGE_POSITIONS.get(seq)
        year = years[seq % len(years)]
        cover_date = f"{year}-{(seq % 12) + 1:02d}-01"
        doi = f"10.1109/tpami.{year}.{2_000_000 + seq:07d}"
        subtype, subtype_desc, aggregation = (
            ("ar", "Article", "Journal")
            if seq % 5 != 0
            else ("cp", "Conference Paper", "Conference Proceedings")
        )

        spec = RecordSpec(
            seq=seq,
            scopus_id=_make_scopus_id(seq, edge),
            year=year,
            cover_date=cover_date,
            doi=doi,
            subtype=subtype,
            subtype_description=subtype_desc,
            aggregation_type=aggregation,
            edge=edge,
        )

        if edge == "partial_year":
            spec.year = 2026
            spec.cover_date = "2026-01-05"
        elif edge in ("duplicate_doi_a", "duplicate_doi_b"):
            spec.doi = DUPLICATE_DOI_VALUE
        elif edge == "non_english":
            spec._language = "German"
        elif edge == "unmapped_country":
            spec._country_override = _UNMAPPED_INSTITUTION

        specs.append(spec)
    return specs


def render_entry(rng: Random, spec: RecordSpec) -> dict[str, Any]:
    """Render one :class:`RecordSpec` into a Scopus-shaped ``entry`` dict."""
    scopus_id = spec.scopus_id

    if spec.edge == "unmapped_country":
        institutions = [spec._country_override]
    elif spec.edge == "many_authors":
        institutions = [rng.choice(_INSTITUTIONS), rng.choice(_INSTITUTIONS)]
    else:
        institutions = rng.sample(_INSTITUTIONS, rng.choice([1, 1, 2]))

    affiliation_afids = [inst[0] for inst in institutions]
    affiliations = [
        _make_affiliation(inst, scalar_afid=(spec.edge == "scalar_afid")) for inst in institutions
    ]

    author_count = 45 if spec.edge == "many_authors" else rng.choice([2, 2, 3, 3, 4, 5, 6])
    authors = [_make_author(rng, position, affiliation_afids) for position in range(author_count)]

    if spec.edge == "non_english":
        title = (
            "Robuste Erkennung von Anomalien in Videoüberwachungssequenzen: "
            "Ein Vergleichender Ansatz"
        )
        abstract = (
            "In dieser Arbeit wird ein robustes Verfahren zur Erkennung von "
            "Anomalien in Videoüberwachungssequenzen vorgestellt. Das Modell "
            "kombiniert raeumlich-zeitliche Merkmale mit einem selbstueberwachten "
            "Lernverfahren, um normale von auffaelligen Ereignissen zu "
            "unterscheiden. Die Auswertung erfolgt auf mehreren oeffentlichen "
            "Datensaetzen aus dem Bereich der staedtischen Ueberwachung. Die "
            "Ergebnisse zeigen eine konsistente Verbesserung gegenueber "
            "bestehenden Verfahren."
        )
    else:
        title = _make_title(rng, spec.seq)
        abstract = _make_abstract(rng, title)

    entry: dict[str, Any] = {
        "@_fa": "true",
        "link": _entry_links(scopus_id),
        "prism:url": f"https://api.elsevier.com/content/abstract/scopus_id/{scopus_id}",
        "dc:identifier": f"SCOPUS_ID:{scopus_id}",
        "eid": f"2-s2.0-{scopus_id}",
        "dc:title": title,
        "dc:creator": f"{authors[0]['surname']} {authors[0]['initials']}",
        "prism:publicationName": f"{title.split(':')[0][:40]} Proceedings"
        if spec.aggregation_type == "Conference Proceedings"
        else "Journal of Spatiotemporal Pattern Analysis",
        "prism:issn": f"{10000000 + spec.seq:08d}",
        "prism:eIssn": f"{20000000 + spec.seq:08d}",
        "prism:volume": str(10 + (spec.seq % 40)),
        "prism:pageRange": f"{100 + spec.seq}-{120 + spec.seq}",
        "prism:coverDate": spec.cover_date,
        "prism:coverDisplayDate": str(spec.year),
        "citedby-count": str(rng.randint(0, 150)),
        "affiliation": affiliations,
        "prism:aggregationType": spec.aggregation_type,
        "subtype": spec.subtype,
        "subtypeDescription": spec.subtype_description,
        "author-count": {"@limit": "100", "$": str(author_count)},
        "author": authors,
        "source-id": f"{30000 + (spec.seq % 500)}",
        "openaccess": "1" if spec.seq % 4 == 0 else "0",
        "openaccessFlag": spec.seq % 4 == 0,
        "language": spec._language,
    }

    if spec.doi is not None:
        entry["prism:doi"] = spec.doi

    if spec.edge != "no_abstract":
        entry["dc:description"] = abstract

    if spec.edge != "zero_keywords":
        keyword_count = rng.choice([3, 3, 4, 4, 5])
        entry["authkeywords"] = _make_keywords(rng, keyword_count)

    return entry


# ---------------------------------------------------------------------------
# Pagination envelope
# ---------------------------------------------------------------------------


def _cursor_token(label: str) -> str:
    """A deterministic, opaque-looking base64 cursor token."""
    return base64.b64encode(f"prismabib-reference-fixture-cursor-{label}".encode()).decode()


def build_pages(entries: list[dict[str, Any]], *, query: str) -> list[dict[str, Any]]:
    chunks = [entries[i : i + PAGE_SIZE] for i in range(0, len(entries), PAGE_SIZE)]
    tokens = [_cursor_token(str(i)) for i in range(1, len(chunks))]
    # Termination: the last page's @next equals its own @current (see
    # prismabib.sources.scopus.ScopusClient.search's termination check).
    currents = ["*", *tokens]
    nexts = [*tokens, tokens[-1] if tokens else "*"]

    pages: list[dict[str, Any]] = []
    encoded_query = quote(query)
    for index, chunk in enumerate(chunks):
        current = currents[index]
        nxt = nexts[index]
        link = [
            {
                "@_fa": "true",
                "@ref": "self",
                "@href": (
                    f"https://api.elsevier.com/content/search/scopus?cursor={quote(current)}"
                    f"&count=25&query={encoded_query}&view=COMPLETE"
                ),
                "@type": "application/json",
            },
            {
                "@_fa": "true",
                "@ref": "first",
                "@href": (
                    f"https://api.elsevier.com/content/search/scopus?cursor=*"
                    f"&count=25&query={encoded_query}&view=COMPLETE"
                ),
                "@type": "application/json",
            },
        ]
        if index < len(chunks) - 1:
            link.append(
                {
                    "@_fa": "true",
                    "@ref": "next",
                    "@href": (
                        f"https://api.elsevier.com/content/search/scopus?cursor={quote(nxt)}"
                        f"&count=25&query={encoded_query}&view=COMPLETE"
                    ),
                    "@type": "application/json",
                }
            )

        page = {
            "search-results": {
                "opensearch:totalResults": str(len(entries)),
                "opensearch:itemsPerPage": "25",
                "opensearch:Query": {
                    "@role": "request",
                    "@searchTerms": query,
                    "@startPage": "",
                },
                "cursor": {"@current": current, "@next": nxt},
                "link": link,
                "entry": chunk,
            }
        }
        pages.append(page)
    return pages


# ---------------------------------------------------------------------------
# Writing (mirrors src/prismabib/capture/writer.py's exact byte encoding)
# ---------------------------------------------------------------------------


# Deliberately no local encoder. Page files are written by
# `prismabib.capture.writer._write_page`, the exact function a real acquisition
# run uses, so this fixture cannot drift from production Layer 0. It drifted once
# already: the writer changed from "one page = one JSON line" to true JSON Lines
# (one record per line, envelope in a sibling `.meta.json`) and a hand-rolled copy
# here would have kept generating the old shape, testing a format the system no
# longer writes.


def main() -> None:
    rng = Random(SEED)

    specs = build_specs()
    entries = [render_entry(rng, spec) for spec in specs]

    project = Project(slug="reference", root=FIXTURE_ROOT)
    query = build_query_for_project(project)
    criteria_version = project.criteria.version

    pages = build_pages(entries, query=query)

    RUN_DIR.mkdir(parents=True, exist_ok=True)
    payload_files: list[str] = []
    for index, page in enumerate(pages):
        filename = f"page-{index:04d}.jsonl"
        _write_page(RUN_DIR, filename, page)
        payload_files.append(filename)

    digest = hashlib.sha256()
    for filename in payload_files:
        digest.update((RUN_DIR / filename).read_bytes())
    payload_sha256 = digest.hexdigest()

    manifest = RunManifest(
        run_id=RUN_ID,
        started_at=STARTED_AT,
        finished_at=FINISHED_AT,
        endpoint=ScopusClient.SEARCH_ENDPOINT,
        query=query,
        view="COMPLETE",
        total_results=TOTAL_RECORDS,
        pages_fetched=len(payload_files),
        payload_files=payload_files,
        payload_sha256=payload_sha256,
        client_version=CLIENT_VERSION,
        criteria_version=criteria_version,
    )
    # No trailing newline: mirrors capture/writer.py's _atomic_write_bytes call,
    # which writes exactly manifest.model_dump_json(indent=2).encode("utf-8") + b"\n".
    (RUN_DIR / "manifest.json").write_bytes(
        manifest.model_dump_json(indent=2).encode("utf-8") + b"\n"
    )

    print(f"Wrote {len(payload_files)} pages, {TOTAL_RECORDS} records, to {RUN_DIR}")
    print(f"payload_sha256={payload_sha256}")


if __name__ == "__main__":
    main()
